# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='image_check',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
