# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0002_auto_20160828_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='edit_check',
            field=models.BooleanField(default=False),
        ),
    ]
