# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_accountmodel_edit_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='bio',
            field=models.TextField(default=None),
        ),
    ]
