# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_accountmodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='bio',
        ),
    ]
