# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0005_remove_accountmodel_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='account_bio',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
