# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0006_accountmodel_account_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Accountant', 'Accountant'), ('Engineer', 'Engineer'), ('Software', 'Software'), ('Designer', 'Designer')], max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='user_job',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Engineer', 'Engineer'), ('Software', 'Software'), ('Designer', 'Designer')], max_length=25, null=True),
        ),
    ]
