# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0007_auto_20160831_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='manipulate_db',
            field=models.IntegerField(default=1),
        ),
    ]
