# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user_home', '0008_accountmodel_manipulate_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='manipulate_db',
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='all_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
