# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0009_auto_20160831_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsmodel',
            name='all_users',
        ),
        migrations.DeleteModel(
            name='JobsModel',
        ),
    ]
