# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0010_auto_20160831_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
