# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0011_auto_20160831_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountant', models.IntegerField(default=0)),
                ('designer', models.IntegerField(default=0)),
                ('engineer', models.IntegerField(default=0)),
            ],
        ),
    ]
