# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0013_job_list_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(max_length=2000, null=True),
        ),
    ]
