# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0015_accountmodel_user_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='job_list',
            name='dummy_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_home.Dummy'),
        ),
    ]
