# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0019_remove_accountmodel_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='written_review',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
