# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0020_accountmodel_written_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='all_written_reviews',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
