# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0021_accountmodel_all_written_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='all_written_reviews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), null=True, size=None),
        ),
    ]
