# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0022_auto_20160902_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='edit_check',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='image_check',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='written_review',
        ),
    ]
