# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0023_auto_20160902_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={0:0}),
        ),
    ]
