# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:50
from __future__ import unicode_literals
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0024_auto_20160903_0835'),
    ]

    operations = [
        HStoreExtension(),
    ]
