# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0027_auto_20160903_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='dummy_key',
        ),
        migrations.DeleteModel(
            name='Job_List',
        ),
    ]
