# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0029_job_list'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountmodel',
            table='user',
        ),
    ]
