# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0030_auto_20160903_1128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountmodel',
            table=None,
        ),
    ]
