# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0034_remove_accountmodel_all_written_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='dummy_key',
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
