# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire_Review_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, null=True)),
                ('eval', models.FloatField(default=0.0, null=True)),
                ('all', models.FloatField(default=0.0, null=True)),
                ('user_being_reviewed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('written', models.TextField(default=None, max_length=2000, null=True)),
            ],
        ),
    ]
