# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160830_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire_review_model',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
