# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_questionaire_review_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire_review_model',
            name='written',
            field=models.TextField(default=None, max_length=2000, null=True),
        ),
    ]
