# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 22:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_questionaire_review_model_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire_review_model',
            name='all_written_reviews',
            field=django.contrib.postgres.fields.hstore.HStoreField(max_length=2000, null=True),
        ),
    ]
