# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20160903_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire_review_model',
            name='all_written_reviews',
        ),
        migrations.AddField(
            model_name='questionaire_review_model',
            name='written_review',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
