# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20160903_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire_review_model',
            name='all',
        ),
        migrations.RemoveField(
            model_name='questionaire_review_model',
            name='eval',
        ),
    ]
