# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_questionaire_review_model_written'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='written_review_model',
            name='user_being_reviewed',
        ),
        migrations.DeleteModel(
            name='Written_Review_Model',
        ),
    ]
